apiVersion: v1
kind: Service
metadata:
  name: wil-playground-service
  namespace: dev
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 30888
    targetPort: 8888
    protocol: TCP
  selector:
    app: wil-playground