apiVersion: v1
kind: Service
metadata:
  labels:
    app: iot
  name: iot-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: iot
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888