apiVersion: v1
kind: Service
metadata:
  labels:
    app: wil-playground
  name: wil-playground-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: wil-playground
  ports:
  - name: http
    port: 80
    targetPort: 8888
    protocol: TCP
